### ISSUE TITLE
substrate_panic_handler

### ISSUE THREAD

**Issue by roninkaizen** [dothereum/dothereum#37] opened 2019-10-06 16:21 UTC
Version: 0.1.2-x86_64-linux-gnu

stack backtrace:
   0: substrate_panic_handler::set::{{closure}}
   1: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:481
   2: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:384
   3: std::panicking::begin_panic_fmt
             at src/libstd/panicking.rs:339
   4: tokio_timer::wheel::Wheel<T>::poll
   5: tokio_timer::timer::Timer<T,N>::process
   6: <tokio_timer::timer::Timer<T,N> as tokio_executor::park::Park>::park_timeout
   7: <tokio_threadpool::park::boxed::BoxedPark<T> as tokio_executor::park::Park>::park_timeout
   8: tokio_threadpool::worker::Worker::sleep_light
   9: tokio_threadpool::worker::Worker::run
  10: std::thread::local::LocalKey<T>::with
  11: std::thread::local::LocalKey<T>::with
  12: std::thread::local::LocalKey<T>::with
  13: tokio::runtime::threadpool::builder::Builder::build::{{closure}}
  14: std::thread::local::LocalKey<T>::with
  15: std::thread::local::LocalKey<T>::with
  16: std::sys_common::backtrace::__rust_begin_short_backtrace
  17: std::panicking::try::do_call
  18: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:80
  19: core::ops::function::FnOnce::call_once{{vtable.shim}}
  20: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/liballoc/boxed.rs:787
  21: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/liballoc/boxed.rs:787
      std::sys_common::thread::start_thread
             at src/libstd/sys_common/thread.rs:13
      std::sys::unix::thread::Thread::new::thread_start
             at src/libstd/sys/unix/thread.rs:79
  22: start_thread
  23: clone

Thread 'tokio-runtime-worker-0' panicked at 'elapsed=93472017; when=93472013', /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-timer-0.2.11/src/wheel/mod.rs:220

**Comment by soc1c** [comment] 2019-11-02 23:44
duplicate of #36

**Closed by soc1c** 2019-11-02 23:44 UTC
